### ISSUE TITLE
GIST_ID 는 왜 필요한건지 궁금합니다.

### ISSUE THREAD

**Issue by woojg** [techinpark/appstore-status-bot#14]
안녕하세요.
단순한 질문인데 다른 contact point 가 없어서 여기에 문의 드립니다.
1. 예전에는 GIST_ID를 필요로 하지 않다가 추가되었는데 왜 필요한지 궁금합니다.
2. 왜 필요한지 document에 설명이 들어가면 다들 이해하기 좋을 것 같습니다. :)

**Comment by woojg** [comment]
https://fernando.kr/develop/2022-02-13-appstore-status-bot-usage/

**Comment by techinpark** [comment]
@woojg 혹시 블로그의 글이 답변이 되셨을까요?! 
추가로 궁금하신 사항이 있으시면 알려주세요 😃
